name: squawk
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - audioread=2.1.8
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - expat=2.2.6
  - ffmpeg=4.2
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.63.1
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.0
  - joblib=0.14.1
  - jpeg=9b
  - kiwisolver=1.1.0
  - lame=3.100
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libflac=1.3.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libogg=1.3.2
  - libopus=1.3
  - libpng=1.6.37
  - librosa=0.7.2
  - libsndfile=1.0.28
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvorbis=1.3.6
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.31.0
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - numba=0.48.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openh264=1.8.0
  - openssl=1.1.1d
  - pandas=1.0.1
  - pcre=8.43
  - pillow=7.0.0
  - pip=20.0.2
  - pycparser=2.19
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pysoundfile=0.10.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=1.4.0
  - pytz=2019.3
  - qt=5.9.7
  - readline=7.0
  - resampy=0.2.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=45.2.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tbb=2020.0
  - tk=8.6.8
  - torchaudio=0.4.0
  - torchvision=0.5.0
  - tornado=6.0.3
  - tqdm=4.42.1
  - typing=3.6.4
  - wheel=0.34.2
  - x264=1!152.20180806
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - cachetools==4.0.0
    - chardet==3.0.4
    - gast==0.2.2
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.27.2
    - h5py==2.10.0
    - idna==2.9
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - tensorboard==2.1.0
    - tensorflow==2.1.0
    - tensorflow-addons==0.8.2
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - typeguard==2.7.1
    - urllib3==1.25.8
    - werkzeug==1.0.0
    - wrapt==1.12.0
